name: ie-bank-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: didi-fe-dev
  FRONTEND_WEBAPP_UAT: didi-fe-uat
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: didi

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (Development)
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev ## This command builds the Vue.js app using .env.development variables

      - name: Upload artifact for deployment job (Development)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: 'Development'

    steps:
      - name: Download artifact from build-dev job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App - Development'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .

  build-uat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build -- --mode production --dest dist-uat ## This command builds the Vue.js app using .env.uat variables

      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build-uat
    environment:
      name: 'UAT'

    steps:
      - name: Download artifact from build-uat job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App - UAT'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .
